### ISSUE TITLE
NPM peer dependencies fail

### ISSUE THREAD

**Issue by eddiemonge** [yeoman/generator-angular#220]
generator karma was updated to 0.3.0. g-a lists g-k ~0.2.2 as the peer dependency

**Comment by jaimegarcia** [comment]
In my case, I solved by unistalling generator-express-angular:
    npm uninstall -g generator-express-angular

**Comment by rainabba** [comment]
Inspired from #220 (comment) (eddiemonge), I also tried to remove ALL generators (I'm having the exact same issue with generator-angular and generator-socketio now):

```
npm rm -g yo generator-* yeoman-generator bower grunt; npm install -g generator-angular
and still I get:
```

```
npm ERR! code EPEERINVALID
npm ERR! peerinvalid The package generator-karma does not satisfy its siblings' peerDependencies require
```

**Comment by eddiemonge** [comment]
I think npm updated to not install peer dependencies anymore. might have to do that manually now

**Comment by rainabba** [comment]
Thank you. I'm failing to wrap my brain around the issue here then. One of the biggest benefits of NPM to me is dependency handling and that seems to break it (though all this does seem to revolve around generator-karma in particular so maybe the issue is there). Is my perspective off? Also, I try to install generator-karma and still get errors so I can't get anywhere. Any idea what I should be doing?

```
C:\......\node-socketio-test [master]> npm install -g generator-karma
npm WARN peerDependencies The peer dependency yo@>=1.0.0 included from generator-karma will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "generator-karma"
npm ERR! node v0.10.36
npm ERR! npm  v2.6.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package generator-karma does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer generator-angular@0.11.1 wants generator-karma@>=0.9.0
npm ERR! peerinvalid Peer generator-angular-ui-router@0.5.3 wants generator-karma@~0.5.0
npm ERR! peerinvalid Peer generator-angular-xl@0.6.1 wants generator-karma@>=0.6.0
```

**Comment by cmawhorter** [comment]
If you're starting a new project in an empty directory, you might want to make sure you have a `package.json` in the directory.

I don't install anything from npm globally and was still seeing this error. Creating the package.json before running `npm install yo` resolved it for me.

npm -g should really be abolished...

**Comment by rainabba** [comment]
No kidding. I didn't create the package.json because I knew the generator would just overwrite it. That is pretty poor behavior. I also skipped the global approach and now I'm off and running.

Thank you

**Comment by cyrilchaponeverysens** [comment]
@cmawhorter I'm facing some EPEERINVALID. (generator-angular requiring generator-karma, generator-karma requiring yo), do you suggest to install yo and generators locally ?

**Comment by javarch** [comment]
Ich werde ab  16.09.2015 nicht im B�ro sein. Ich kehre zur�ck am
12.10.2015.
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Die R�ckmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [generator-angular] NPM peer dependencies fail (#220)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2015 Agent 'Abwesenheit'

Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
DVR: 0572934, UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angef�hrten Absender via E-Mail
dient ausschlie�lich Informationszwecken. Rechtsgesch�ftliche Erkl�rungen
d�rfen �ber dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.

**Comment by cmawhorter** [comment]
@cyrilchaponeverysens Personally, I've completely dropped `npm -g`.  Instead, I add ./node_modules/.bin to my system path and install locally.

It has required some slight tweaks to my workflow but overall a positive.

After, you can do this to create a project:

```bash
# add "./node_modules/.bin" to your system path
mkdir my-project
cd my-project
echo '{}' > package.json
npm install yo --save
yo # yay. no more dll hell.
```

**Comment by eddiemonge** [comment]
@cmawhorter probably not a good idea to add local bins to your path. you could always do `./node_modules/.bin/yo` or make an alias that somehow does the path part

**Comment by cmawhorter** [comment]
@eddiemonge Any reason in particular you say that?  Since making the change it's all coming up milhouse.

**Comment by eddiemonge** [comment]
Its basically the same thing as installing with -g at that point.

**Comment by cmawhorter** [comment]
Editing path is not the same as -g because it makes npm store the package
locally in the project's node_modules, instead of a shared global space --
which makes juggling version deps cumbersome.

IIRC python had to create an entirely separate virtualenv utility to work
around the problems associated with global package installs.  ...I think
node hails from ruby, but I have no idea how they solved it.

Also.. I'd throw it out there that there are (slight) security implications
with installing any utility globally.

The security implications become much larger when ppl `sudo npm install
-g`, which was commonplace due to the way the nodejs installer worked up
until recently.  Yikes.

**Comment by eddiemonge** [comment]
recently meaning a few years ago? we have always advocated users dont use sudo to isntall npm packages. also, have you looked at npm3?

**Comment by cmawhorter** [comment]
Quoted from the npmjs.com Getting Started
<https://docs.npmjs.com/getting-started/installing-npm-packages-globally>
updated May '15:

If you get an EACCES error, you will want to fix your permissions or try
> again with sudo:
> sudo npm install -g jshint


O.O ... Also this
<https://www.google.com/search?q=%22sudo+npm+install+-g%22&num=100&espv=2&biw=1436&bih=805&source=lnt&tbs=qdr:m&sa=X&ved=0CBQQpwVqFQoTCKzv8ciOscgCFcYriAod4ekD1A>.
And I can't find it now -- so I'm likely full of shit -- but I remember
reading earlier this year about malware actively exploiting weak packages
installed with -g.

Ripples are more than still being felt.  I can still see the splash.

I haven't looked at npm v3.0 yet.  Does it remove -g?

**Comment by eddiemonge** [comment]
No but it handles dependencies better

**Comment by ravigithub** [comment]
can anyone please help me, now installing node packages on my new project and so when i hit the 'NPM INSTALL' it gets error like "peer dependencies blah...blah" like that.. so any one could help me and get rid of this problem, i highly appreciate for your answers and that's gonna be a great full....thanks.
